ezpublish:
    system:
        site_group:
            pagelayout: "@ezdesign/pagelayout.html.twig"

            content_view:
                full:
                    inspiration_list:
                        template: "@ezdesign/full/inspiration_list.html.twig"
                        match:
                            Id\Location: 2
                            Identifier\ContentType: [folder]
